---
name: Lint codebase
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install Poetry
        run: pip install poetry

      - name: Install poetry
        run: pipx install poetry

      - name: cache poetry environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry'

      - name: install package
        run: poetry install --with lint --with test

      - name: cache pre-commit environment
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit||${{ hashFiles('.pre-commit-config.yaml') }}

      - name: run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure --color=always
